version: '3.8'

services:
  postgres:
    container_name: ing-interview
    image: postgres:14.7
    environment:
      POSTGRES_DB: storemanagerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
